In [1]:
import tensorflow as tf
import numpy as np

# Tensor Initialization and Casting

### Constant

In [ ]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

In [ ]:
tensor_one_d = tf.constant([2, 0, -3])
tensor_one_d

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3,5,-1]
])
tensor_two_d

### ndim, shape, size

In [ ]:
tensor_two_d.ndim

In [ ]:
tensor_two_d.shape

In [ ]:
tf.size(tensor_two_d)

### Create with type

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3,5,-1]
], dtype=tf.float32)
tensor_two_d

### casting

In [ ]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.float32)
casted_tensor_one_d

### numpy array to tensor

In [ ]:
np_array = np.array([1, 2, 4])
np_array

In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

### eye, fill, ones, ones_like, zeros, zeros_likea

In [ ]:
tf.eye(3)

In [ ]:
tf.fill([2, 3], 9)

In [ ]:
tf.ones([2, 3])

In [ ]:
tf.zeros([2, 3])

### random

In [ ]:
tf.random.normal([2, 3])

In [ ]:
tf.random.uniform([2, 3])

#### seed

In [ ]:
tf.random.set_seed(42)
print(tf.random.normal([2, 3]))

tf.random.set_seed(42)
print(tf.random.normal([2, 3]))

# Indexing (Slicing)

In [ ]:
t = tf.constant([3, 6, 2, 4, 6, 66, 7])
t

In [ ]:
t[1: 4]

In [ ]:
t[1: 4: 2]

### ...

In [ ]:
t = tf.random.uniform([4, 2, 3], minval=0, maxval=100, dtype=tf.int32)
t

In [ ]:
t[..., 1]

In [ ]:
t[:, :, 1]

# Linear Algebra Operations

### [tf.linalg module](https://www.tensorflow.org/api_docs/python/tf/linalg)

### tf.linalg.matmul with Matrix with Batch Dimension (3-dim)

In [2]:
x1 = tf.random.normal([3, 2, 3])
x2 = tf.random.normal([3, 2, 3])

Metal device set to: Apple M1 Max


2023-10-19 09:34:01.887932: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-10-19 09:34:01.894821: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [6]:
tf.linalg.matmul(x1, x2, transpose_a=True)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-3.330759  , -0.9333693 ,  2.0767367 ],
        [ 1.7682849 ,  0.6414715 , -1.1990327 ],
        [ 1.8185508 ,  1.5894356 , -1.8478574 ]],

       [[ 2.326621  ,  0.9110201 ,  0.43098068],
        [-0.8021616 , -0.24001458,  0.07046518],
        [-3.4481125 , -1.1116396 ,  0.06654787]],

       [[ 1.1427337 , -0.67321956,  1.0959303 ],
        [ 1.6140544 , -0.10834458,  1.0024302 ],
        [-0.5019271 , -0.3509419 , -0.0626919 ]]], dtype=float32)>

### adjoint : Transpose and conjugate
### band_part : Set some elements to zero according to condition

# Ragged Tensors

다양한 길이의 vector를 하나의 tensor에 저장

In [8]:
tensor_ragged = tf.ragged.constant([[1,2,0],
                                    [3],
                                    [1,5,6,5,6],
                                    [2,3]])
tensor_ragged

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>

# Sparse Tensors

# String Tensors

In [11]:
tensor_string = tf.constant(["Hello", "I am", "a string"])
tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Hello', b'I am', b'a string'], dtype=object)>

# Variables

### initialize

In [13]:
x_var = tf.Variable([1, 2])
x_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [14]:
x_var = tf.Variable(tf.constant([1, 2]))
x_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

### assign

In [15]:
v = tf.Variable(1.)
v.assign(2.)
print(v)
v.assign(0.5)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.5>


### CPU or GPU

In [16]:
v.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [18]:
with tf.device("GPU:0"):
    x_var = tf.constant([1, 2])
    print(x_var.device)
    
with tf.device("CPU:0"):
    x_var = tf.constant([1, 2])
    print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [19]:
with tf.device("CPU:0"):
    x1 = tf.constant([1, 2, 3])
    x2 = tf.constant([1])
    
with tf.device("GPU:0"):
    x3 = x1 + x2
    
print(x1, x1.device)
print(x2, x2.device)
print(x3, x3.device)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:GPU:0
