In [22]:
import tensorflow as tf
import numpy as np

# Tensor Initialization and Casting

### Constant

In [14]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [16]:
tensor_one_d = tf.constant([2, 0, -3])
tensor_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, -3], dtype=int32)>

In [18]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3,5,-1]
])
tensor_two_d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1]], dtype=int32)>

### ndim, shape, size

In [19]:
tensor_two_d.ndim

2

In [33]:
tensor_two_d.shape

TensorShape([2, 3])

In [34]:
tf.size(tensor_two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

### Create with type

In [20]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3,5,-1]
], dtype=tf.float32)
tensor_two_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  2.,  0.],
       [ 3.,  5., -1.]], dtype=float32)>

### casting

In [21]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.float32)
casted_tensor_one_d

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.,  0., -3.], dtype=float32)>

### numpy array to tensor

In [23]:
np_array = np.array([1, 2, 4])
np_array

array([1, 2, 4])

In [24]:
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 4])>

### eye, fill, ones, ones_like, zeros, zeros_likea

In [27]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [28]:
tf.fill([2, 3], 9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [29]:
tf.ones([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### random

In [35]:
tf.random.normal([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7474821 , -0.43480277, -2.3380415 ],
       [ 1.4921113 , -0.02339826,  0.65085155]], dtype=float32)>

In [36]:
tf.random.uniform([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.1492256 , 0.6199831 , 0.46032953],
       [0.3097217 , 0.5305011 , 0.1192795 ]], dtype=float32)>

#### seed

In [37]:
tf.random.set_seed(42)
print(tf.random.normal([2, 3]))

tf.random.set_seed(42)
print(tf.random.normal([2, 3]))

tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)


# Indexing (Slicing)

In [38]:
t = tf.constant([3, 6, 2, 4, 6, 66, 7])
t

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 3,  6,  2,  4,  6, 66,  7], dtype=int32)>

In [39]:
t[1: 4]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 2, 4], dtype=int32)>

In [44]:
t[1: 4: 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 4], dtype=int32)>

### ...

In [52]:
t = tf.random.uniform([4, 2, 3], minval=0, maxval=100, dtype=tf.int32)
t

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[98, 43, 19],
        [94, 32, 13]],

       [[84, 42, 86],
        [24, 81, 63]],

       [[46,  0, 69],
        [69,  0, 81]],

       [[24, 97, 80],
        [18, 41, 96]]], dtype=int32)>

In [53]:
t[..., 1]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[43, 32],
       [42, 81],
       [ 0,  0],
       [97, 41]], dtype=int32)>

In [55]:
t[:, :, 1]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[43, 32],
       [42, 81],
       [ 0,  0],
       [97, 41]], dtype=int32)>